baseURL = "/"
languageCode = "en-us"
title = "Eclipse Mita"
theme = "hugo-material-docs"
metadataformat = "yaml"
relativeURLs = true
Paginate = 4
PygmentsCodeFences = true
PygmentsUseClasses = true
PygmentsStyle = "monokai"
canonifyurls = true

[blackfriday]
  smartypants = true
  fractions = true
  smartDashes = true
  plainIDAnchors = true
  extensions = [ "fencedCode", "backslashLineBreak" ]

[params]
	# General information
	description = "The documentation of Eclipse Mita."
	copyright = "The Eclipse Mita Project"

	logo = "images/mita.svg"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = [ "css/custom.css" ]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue-grey"
    	accent  = "light-blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	twitter = "eclipse_mita"
	github  = "eclipse/mita"

[[menu.main]]
    name = "Download"
    weight = -400
    url = "http://github.com/eclipse/mita"
[[menu.main]]
    name = "Concepts"
    weight = -300
    url = "concepts/"
[[menu.main]]
    name = "Language"
    weight = -200
    url = "language/"
[[menu.main]]
    name = "Platforms"
    weight = -100
    url = "platforms/"
